### ISSUE TITLE
Arenastats not working since wotlk

### ISSUE THREAD

**Issue by spectral2702** [denishamann/ArenaStats#18]
Hello, good evening.

Sadly since wotlk, my arenastats doesnt work anymore :( it worked well without any problems during the whole tbc classic addon. 

I Currently tried every single way to fix it, from installing it multiple times and deleting it multiple times, downloading from different sources, nearby everything that did come in my mind i tried and nothing worked, sadly. I noticed that it recorded random 3 games but since then it did never recorded any 2s/3s/5s ranked or unranked. If i can give any information about my speccs let me pls know.

thanks and regards

**Comment by Simon3** [comment]
Hello, I'm not playing wotlk at the moment but we can try to troubleshoot this: 
- Do you know if this problem is affecting other people, or just you? 
- So if I understand correctly, you have the ArenaStats minimap icon, you can click on it, you can see a few old matches (tbc or wotlk matches?), but no new match has been recorded for a long time, correct?
- Did you try to delete your local database (deleting the following file: `C:\Program Files (x86)\World of Warcraft\_classic_\WTF\Account\ACCOUNT_NAME\SavedVariables\ArenaStats.lua`)? It might be corrupted for some reason. 
- Do you have any lua error when exiting an arena? (use `/console ScriptErrors 1` to enable lua errors, then queue an arena)
- Do you see a message in your chat when you exit an arena? (something like "ArenaStat recorded one arena").

**Comment by spectral2702** [comment]
Hey thank you for your time and sorry for my late response!
So i try to answer as precise as i can.

> I spoke with several people that also using the same addon (around 3-4 peoples) and im the only one affected with the issue

> Yes, correct. I see the minimap icon and click on it the arenastats window opens, i see the ui for settings in the addons, i did see 3 wotlk games randomly recorded. Right, no new match has been recorded for a long time, for the moment there is 0 games visible because i cleaned the games/reinstalled it.

> Yes i just tried to delete it, restarted the game, qued an skirmish, nothing recorded. Deleted every arenastats.lua folder and deleted the addon and reinstalled it again, qued for another skirmish and no game recorded.

> I dont see any message in chat when i exit any arena matches not ranked and not unranked

> As i mentioned above i qued some skirmish during the troubleshoot and did got some lua errors after i did used the /console script. And now i remember that i suggested arenastats and old friend that restarted with wotlk and had do delete the addon because off lua erros after the matches.

I hope that maybe helps, if you need a screenshot from the lua error let me know i will upload it as fast as possible.

regards

**Comment by Simon3** [comment]
A possible explanation is that there would be a conflict between ArenaStats and another addon. 
Can you copy/paste the content (or post the screenshots) of all the lua errors you get about Arenastats? e.g. when you leave an arena.

**Comment by spectral2702** [comment]
![WoWScrnShot_010523_230059](https://user-images.githubusercontent.com/121644318/210888492-1b4b2f03-f1bb-4276-b7db-a3bdedb659f4.jpg)
![WoWScrnShot_010523_230102](https://user-images.githubusercontent.com/121644318/210888501-4ee97a2d-da76-4e37-9dc1-b768db5ef174.jpg)
![WoWScrnShot_010523_230104](https://user-images.githubusercontent.com/121644318/210888508-98219104-dc5c-414e-9780-f5a82e218358.jpg)
 here are another one with 3 pages of lua erros after 1 game

**Comment by denishamann** [comment]
Fixed in version 0.2.2, you can download it or it will be available on curse very soon.
